name: Villagerlimit
version: '2.1.1'
main: org.pvp.villagerlimit.Villagerlimit
api-version: '1.21'
author: Ti_Avanti
description: 一个限制村民功能的插件，支持数据持久化、多语言、GUI界面
softdepend: [PlaceholderAPI]
commands:
  killvillagers:
    description: 移除所有已加载的村民
    usage: /killvillagers
    permission: villagerlimit.kill
  vlreload:
    description: 重载插件配置
    usage: /vlreload
    permission: villagerlimit.admin
  vlstats:
    description: 查看交易统计
    usage: /vlstats [玩家名]
    permission: villagerlimit.stats
  vltop:
    description: 查看交易排行榜
    usage: /vltop
    permission: villagerlimit.top
  vladmin:
    description: 管理命令
    usage: /vladmin <reset|clear> [玩家名]
    permission: villagerlimit.admin
  vlperf:
    description: 查看性能统计
    usage: /vlperf [cache|memory|threads|tracker|cleanup]
    permission: villagerlimit.admin
permissions:
  villagerlimit.kill:
    description: 允许使用killvillagers命令
    default: op
  villagerlimit.admin:
    description: 管理员权限
    default: op
  villagerlimit.stats:
    description: 查看交易统计权限
    default: true
  villagerlimit.stats.others:
    description: 查看其他玩家统计权限
    default: op
  villagerlimit.top:
    description: 查看排行榜权限
    default: true
  villagerlimit.trade.vip:
    description: VIP交易权限
    default: false
  villagerlimit.trade.svip:
    description: SVIP交易权限
    default: false
  villagerlimit.trade.admin:
    description: 管理员交易权限
    default: op
